version: '3.3'

volumes:
  data:

services:  

  myadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=${MYSQL_HOST}
    depends_on:
      - db
    networks:
      - app-networks

  db:
    image: mysql:${MYSQL_VERSION}
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - data:/var/lib/mysql
    env_file:
      - ".env"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - app-networks

  redis:
    image: redis:${REDIS_VERSION}
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
    networks:
      - app-networks

  app:
    build: .
    container_name: ${NAME_APP_WEB}
    ports:
      - "8000:80"
      - "3000:443"
    restart: always
    depends_on:
      - db
      - redis
    volumes:
      - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./src:/usr/share/nginx"
      - "./setup.sh:/usr/share/nginx/setup.sh"
      - "./etc/ssl:/etc/ssl"
    networks:
      - app-networks

networks:
  app-networks:
    driver: bridge